### ISSUE TITLE
Can't install due to version of script.module.requests

### ISSUE THREAD

**Issue by sengsational** [Silicondust/script.hdhomerun.view#1]
I downloaded a zip file from here: https://kodi.tv/addon/scripts-video-add-ons/hdhomerun
But when I try to add it, I get "The dependency on script.module.requests version 2.3..." and it does not complete the process.

**Comment by NedScott** [comment]
Does it work if you install the add-on from the Kodi.tv add-on repo?

**Comment by sengsational** [comment]
Thanks NedScott.  The problem was that my LibreELEC build had corruption, so my network access was not working.  Once I got that fixed, then the dependencies loaded fine.  This issue is resolved.
